name: birthday_app
description: A Birthday Tracking App
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: packages/core
  api_mock:
    path: packages/api_mock

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3
  # graphql: ^5.0.1-beta.3
  # fresh_graphql: ^0.5.1
  flutter_blurhash: ^0.7.0
  cached_network_image: ^3.2.0
  path_provider: ^2.0.8
  state_notifier: ^0.7.1
  freezed_annotation: ^2.0.3
  flutter_riverpod: ^2.0.0-dev.0
  faker: ^2.0.0

  very_good_infinite_list: ^0.4.0
  intl: ^0.17.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  build_runner: any

flutter:
  uses-material-design: true
