name: birthday_app
description: A Birthday Tracking App
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3
  isar: ^1.0.5
  isar_flutter_libs: ^1.0.0
  isar_connect: ^1.0.0
  graphql: ^5.0.1-beta.3
  fresh_graphql: ^0.5.1
  flutter_blurhash: ^0.6.0
  cached_network_image: ^3.2.0
  path_provider: ^2.0.8
  state_notifier: ^0.7.1
  freezed_annotation: ^1.1.0
  flutter_riverpod: ^2.0.0-dev.0

  # see analysis_options.yaml
  dart_code_metrics: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  isar_generator: ^1.0.0
  freezed: ^1.1.0
  build_runner: any

flutter:
  uses-material-design: true
